### ISSUE TITLE
expand discussion of collection models

### ISSUE THREAD

**Issue by balmas** [RDACollectionsWG/specification#16]
expand discussion of collection models
- need diagrams from 2-pager added
- scenarios for use of different models
- discussion of ontology

**Comment by balmas** [comment]
Trait section needs to be updated as part of this.  Notes from Javier:

In "Trait: Insertions allowed”: both operations can be replaced by “Insert at (index)”
In “Trait: Shrinkable”: property “no deletes” would lead to a double negative expression. If needed, replace by "deletes-allowed” or something similar. But why not to use the “read-only” property?
"The collection membership is a finite set of collection item identifiers” Probably replace “set” by “group”; or “set/list”

**Comment by TobiasWeigel** [comment]
Thoughts:
* is the whole concept as it was 1 yr ago still up to date with recent discussions ~P9?
* how are the models actually implementable via the API? Also need to look into the wiki.
* scenarios - scavenge driving elements from use cases
* ontology discussion might be some first general steps on how to align collections and their links with ontology engineering approaches.
