### ISSUE TITLE
Naming and organization should be coherent through the different docs and in the graphic.

### ISSUE THREAD

**Issue by balmas** [RDACollectionsWG/specification#2]
From Javier Quniteros:

For instance, the concept “metadata” is present in the Swagger only once “metadataIsMutable”, so what is exactly “metadata". There we refer to the “properties”. Probably we should reduce the number of concepts with a formal meaning in the document to the ones that are used in the JSON representation of the Collection/Member. So many subdivisions do not help. In the Swagger page it’s much clear. I would suggest to go for a description in the document that goes closer to what we have at the Swagger description.

**Comment by TobiasWeigel** [comment]
metadataIsMutable: This should only be understood as covering collection properties, not properties at the member level. So the best way would be to change this to "propertiesAreMutable". We could also leave it at the current name and only update the description, but that leaves a level of ambiguity for implementors if they don't follow every word in the docs.

**Comment by balmas** [comment]
I agree. We should change CollectionObject.metadataIsMutable to CollectionOption.propertiesAreMutable.
