### ISSUE TITLE
Leave AAI discussion out, or simplify

### ISSUE THREAD

**Issue by balmas** [RDACollectionsWG/specification#6]
From Javier Quniteros:

There is no need to be so specific in the names of the roles. In fact, to my understanding that is completely irrelevant for the operation of such a system. In any case, a user logs in, tries to do something and is authorized (or not) by the system. We should not mess up the specification with the “internal management” of the roles (if any). What if I want a completely open system with “read-only” collections? I need no AAI system for that. Any user can create a collection and no one can delete anything. Even the concept of owner could disappear! (I know it’s extreme).

And what if instead of roles I would like to have a user-based ACL (no roles at all)?

Again, all this could remain internal and implementation specific. We have no idea how to send the AuthN information to the system. It could be SSO, but it could also be digest auth, or a code, etc. A client trying to use the system needs to know *only* how to identify itself (out of the scope of this document), and which operations exist to be executed. If the client cannot execute some method, it will receive a 401 http code and it will be clear for it that there is a problem with permissions.

**Comment by TobiasWeigel** [comment]
tw: will also look at this - stuff in master branch is still status of discussion from 1 year ago.
